
CREATE TABLE CITIES (
    CITY CHAR(20),
    STATE CHAR(20),
    PRIMARY KEY (CITY)
);

CREATE TABLE WAREHOUSES (
    WID INTEGER PRIMARY KEY,
    WNAME CHAR(30),
    LOCATION CHAR(20),
    EXTRA_CONTEXT JSON,
    CITY CHAR(20),
    FOREIGN KEY (CITY) REFERENCES CITIES(CITY)
);

CREATE TABLE STORES (
    SID INTEGER PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20),
    WID INTEGER,
    FOREIGN KEY (LOCATION_CITY) REFERENCES CITIES(CITY),
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

CREATE TABLE CUSTOMER (
    CNO INTEGER PRIMARY KEY,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20),
    FOREIGN KEY (CU_CITY) REFERENCES CITIES(CITY)
);

CREATE TABLE ORDERS (
    ONO INT PRIMARY KEY,
    ODATE DATE,
    CNO INTEGER,
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

CREATE TABLE ITEMS (
    ITEMNO INTEGER PRIMARY KEY,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2)
);

CREATE TABLE ITEM_ORDERS (
    ITEMNO INTEGER,
    ONO INT,
    ORDERED_QUANTITY INT,
    PRIMARY KEY (ITEMNO, ONO),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO)
);

CREATE TABLE STORE_ITEMS (
    SID INTEGER,
    ITEMNO INTEGER,
    QUANTITY INT,
    PRIMARY KEY (SID, ITEMNO),
    FOREIGN KEY (SID) REFERENCES STORES(SID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);
